export default function Disclaimer() {
  return (
    <div className="border-l-4 border-gold bg-yellow-50 p-4 my-6 text-sm text-charcoal rounded-r-md">
      <p className="font-semibold mb-1">This is not legal advice.</p>
      <p>
        The information here is generated by AI based on publicly available
        sources and may be incomplete or out of date. For urgent voter rights
        issues, call the national Election Protection hotline:{" "}
        <a href="tel:+18666687683" className="font-bold underline">
          1-866-OUR-VOTE
        </a>
        .
      </p>
    </div>
  );
}
