import { NextRequest, NextResponse } from "next/server";
import { anthropic, DEFAULT_MODEL } from "@/lib/anthropic";

export const runtime = "nodejs";
export const maxDuration = 30;

type RightsRequest = {
  state: string;
  zip?: string;
  voterType: string;
};

const VOTER_TYPES: Record<string, string> = {
  "first-time": "first-time voter",
  returning: "returning voter who has voted before",
  "formerly-incarcerated":
    "voter who was formerly incarcerated and wants to confirm their voting rights are restored",
  "college-student": "college student voting from a campus address",
  "moved-recently": "voter who has moved within the last 12 months",
  disability:
    "voter with a disability who may need accommodations at the polling place",
};

function buildPrompt({ state, zip, voterType }: RightsRequest) {
  const voterDescription =
    VOTER_TYPES[voterType] || "voter looking for general voting rights information";

  return `You are a voter rights assistant for Hold The Line 2026, a non-partisan voter protection project. A ${voterDescription} in ${state}${
    zip ? ` (ZIP ${zip})` : ""
  } is asking for a personalized rights summary for the 2026 elections.

Produce a clear, plain-English one-page guide as Markdown with the following sections, in this order. Be specific to ${state} where you can. If you are not confident about a specific ${state} rule, say so plainly and recommend they verify with their Secretary of State or call 1-866-OUR-VOTE — do not guess.

## The Basics for ${state}
A short paragraph (3-4 sentences) on the most important things this voter should know about voting in ${state} right now, including what recent law changes (2024-2026) affect them.

## How to Register or Confirm Your Registration
Step-by-step. Include the ${state} Secretary of State website if you know it.

## ID Requirements
Exactly what ID is required at the polls in ${state}, what counts, what does not, and what alternatives exist if they do not have ID.

## Mail-in Voting in ${state}
Who is eligible, deadlines, witness/signature requirements, how to track your ballot, and the rejection-rate risk if known. Recommend in-person early voting instead if ${state} has a history of high mail ballot rejection.

## In-person Voting
Polling hours, early voting window, and how to find your polling place.

## Top Three Things to Watch Out For
The three highest-risk issues for ${voterDescription}s in ${state} in 2026 — be concrete. (e.g., specific recent law, known long-line precincts, recent purges, polling closures.)

## If You Are Turned Away
The three immediate steps: provisional ballot, call 1-866-OUR-VOTE, document everything.

End with a short paragraph reminding the voter that this is generated by AI, may be incomplete, and that 1-866-OUR-VOTE is the authoritative resource on Election Day.

Tone: direct, warm, urgent without being alarmist. No headers above ## level (do not use h1). No emojis. Use bold sparingly for the most important phrases. Keep it under 700 words.`;
}

export async function POST(req: NextRequest) {
  try {
    const body = (await req.json()) as RightsRequest;

    if (!body.state) {
      return NextResponse.json(
        { error: "State is required." },
        { status: 400 }
      );
    }
    if (!body.voterType) {
      return NextResponse.json(
        { error: "Voter type is required." },
        { status: 400 }
      );
    }

    const message = await anthropic.messages.create({
      model: DEFAULT_MODEL,
      max_tokens: 1500,
      messages: [
        {
          role: "user",
          content: buildPrompt(body),
        },
      ],
    });

    const textBlock = message.content.find((c) => c.type === "text");
    const text = textBlock && "text" in textBlock ? textBlock.text : "";

    return NextResponse.json({
      ok: true,
      markdown: text,
    });
  } catch (err) {
    console.error("[api/rights] error", err);
    return NextResponse.json(
      {
        ok: false,
        error:
          "Something went wrong generating your guide. Please call 1-866-OUR-VOTE for help.",
      },
      { status: 500 }
    );
  }
}
